services:

    LSB\PaymentBundle\Manager\PaymentManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$payum": '@payum'

    LSB\PaymentBundle\Manager\PaymentTokenManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$payum": '@payum'
