services:

    LSB\PaymentBundle\Repository\PaymentRepository:
        arguments:
            - '@doctrine'
    LSB\PaymentBundle\Repository\PaymentRepositoryInterface: '@LSB\PaymentBundle\Repository\PaymentRepository'

    LSB\PaymentBundle\Repository\PaymentTokenRepository:
        arguments:
            - '@doctrine'
    LSB\PaymentBundle\Repository\PaymentTokenRepositoryInterface: '@LSB\PaymentBundle\Repository\PaymentTokenRepository'

    LSB\PaymentBundle\Repository\MethodRepository:
        arguments:
            - '@doctrine'
    LSB\PaymentBundle\Repository\MethodRepositoryInterface: '@LSB\PaymentBundle\Repository\MethodRepository'

    LSB\PaymentBundle\Repository\MethodTranslationRepository:
        arguments:
            - '@doctrine'
    LSB\PaymentBundle\Repository\MethodTranslationRepositoryInterface: '@LSB\PaymentBundle\Repository\MethodTranslationRepository'
